export const sampledata = [
  {
    id: 1,
    name: "sarah Graham",
    role: "user",
    email: "Sincere@april.biz",
    status: "active",
    profile: "https://picsum.photos/200/300",
  },
  {
    id: 2,
    name: "christian lahm",
    role: "user",
    email: "joy@anne.com",
    status: "active",
    profile: "https://picsum.photos/200/300",
  },
  {
    id: 3,
    name: "nickolas gusto",
    role: "guest",
    email: "Sincere@april.biz",
    status: "inactive",
    profile: "https://picsum.photos/200/300",
  },
  {
    id: 4,
    name: "samuel stones",
    role: "user",
    email: "Sincere@april.biz",
    status: "active",
    profile: "https://picsum.photos/200/300",
  },
  {
    id: 5,
    name: "jonathan gomez",
    role: "user",
    email: "Sincere@april.biz",
    status: "active",
    profile: "https://picsum.photos/200/300",
  },
  {
    id: 6,
    name: "esther phil",
    role: "user",
    email: "Sincere@april.biz",
    status: "inactive",
    profile: "https://picsum.photos/200/300",
  },
  {
    id: 7,
    name: "jones adam",
    role: "user",
    email: "Sincere@april.biz",
    status: "inactive",
    profile: "https://picsum.photos/200/300",
  },
  {
    id: 8,
    name: "Leanne Graham",
    role: "admin",
    email: "Sincere@april.biz",
    status: "active",
    profile: "https://picsum.photos/200/300",
  },
  {
    id: 9,
    name: "Newton louis",
    role: "guest",
    email: "Sincere@april.biz",
    status: "inactive",
    profile: "https://picsum.photos/200/300",
  },
];
